# Generated by Django 4.2.6 on 2023-10-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='right_answer',
            field=models.BooleanField(default=False),
        ),
    ]
